export const routes = {
  home: "/",
  stats: "/admin/estadisticas",
  reports: "/admin/reportes",
  notifications: "/admin/notificaciones",
  products: "/admin/productos",
  users: "/admin/usuarios",
  admingastronomy: "/admin/bodegas/admingastronomy",
  adminagro: "/admin/bodegas/adminagro",
  admincoffe: "/admin/bodegas/admincoffe",
  warehouses: "/admin/bodegas",
  configuration: "/admin/configuracion",
  warehousesDetail: "/admin/bodegas/:id",
  help: "/admin/ayuda",
  profile: "/admin/perfil",
  logout: "/admin/cerrar-sesion",
  login: "/login",
  admin: "/admin",
  root: "..",
};