export const routes = {
  home: "/",
  stats: "/admin/estadisticas",
  entrada: "/admin/entrada",
  salida: "/admin/salida",
  inventario: "/admin/inventario",
  trazabilidad: "/admin/trazabilidad",
  vencimientos: "/admin/vencimientos",
  StaticE: "/admin/StaticE",
  StacticS: "/admin/StacticS",
  StacticI: "/admin/StacticI",
  StacticT: "/admin/StacticT",
  StacticV: "/admin/StacticV",
  notifications: "/admin/notificaciones",
  products: "/admin/productos",
  detalles:"/admin/detalles",
  users: "/admin/usuarios",
  admingastronomy: "/admin/bodegas/admingastronomy",
  adminagro: "/admin/bodegas/adminagro",
  admincoffe: "/admin/bodegas/admincoffe",
  warehouses: "/admin/bodegas",
  configuration: "/admin/configuracion",
  warehousesDetail: "/admin/bodegas/:id",
  help: "/admin/ayuda",
  profile: "/admin/perfil",
  logout: "/admin/cerrar-sesion",
  login: "/login",
  admin: "/admin",
  root: "..",
};